# Generated by Django 3.2.8 on 2021-10-31 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarter',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_headquarter', to='layout.location'),
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='headquarters',
            field=models.ManyToManyField(related_name='headquarter_service_offered', to='layout.Headquarter'),
        ),
        migrations.AddField(
            model_name='staff',
            name='Headquarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headquarter_staff', to='layout.headquarter'),
        ),
    ]
