# Generated by Django 3.2.8 on 2021-11-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_auto_20211030_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('headquarters', models.ManyToManyField(related_name='headquarter_crisis_scenario', to='layout.Headquarter')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('recovery_time', models.DurationField()),
                ('criticality', models.SmallIntegerField(null=True)),
                ('headquarters', models.ManyToManyField(related_name='headquarter_organization_activity', to='layout.Headquarter')),
                ('scale', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_organization_activity', to='layout.scale')),
            ],
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='recovery_time',
            field=models.DurationField(default='1 day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceoffered',
            name='profit',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='ServiceUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('spending', models.FloatField()),
                ('recovery_time', models.DurationField()),
                ('criticality', models.SmallIntegerField(null=True)),
                ('headquarters', models.ManyToManyField(related_name='headquarter_service_used', to='layout.Headquarter')),
                ('scale', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_service_used', to='layout.scale')),
                ('services_offered', models.ManyToManyField(related_name='service_offered_service_offered', to='layout.ServiceOffered')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('headquarters', models.ManyToManyField(related_name='headquarter_risk', to='layout.Headquarter')),
                ('organizacion_activities', models.ManyToManyField(related_name='organizacion_activity_risk', to='layout.OrganizationActivity')),
                ('services_offered', models.ManyToManyField(related_name='service_used_risk', to='layout.ServiceUsed')),
                ('staffs', models.ManyToManyField(related_name='staff_risk', to='layout.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='organizationactivity',
            name='services_offered',
            field=models.ManyToManyField(related_name='service_offered_organizacion_activity', to='layout.ServiceOffered'),
        ),
        migrations.CreateModel(
            name='IncidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('crisis_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_scenario_indicent_history', to='layout.crisisscenario')),
            ],
        ),
        migrations.AddField(
            model_name='crisisscenario',
            name='risks',
            field=models.ManyToManyField(related_name='crisis_scenario_risk', to='layout.Risk'),
        ),
    ]
