# Generated by Django 3.2.8 on 2021-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_auto_20211101_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisscenario',
            name='description',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
