# Generated by Django 3.2.8 on 2022-01-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_crisisscenario_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crisisscenario',
            old_name='risks',
            new_name='_risks',
        ),
        migrations.AlterField(
            model_name='crisisscenario',
            name='_risks',
            field=models.ManyToManyField(db_column='risks', related_name='crisis_scenario_risk', to='layout.Risk'),
        ),
    ]
