# Generated by Django 3.2.8 on 2022-06-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='services_offered',
            new_name='services_used',
        ),
    ]
