# Generated by Django 3.2.8 on 2022-07-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('bcm_phase2', '0001_initial'),
        ('bcm_phase1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='staffs',
            field=models.ManyToManyField(related_name='staff_risk', to='bcm_phase2.Staff'),
        ),
        migrations.AddField(
            model_name='crisisscenario',
            name='_risks',
            field=models.ManyToManyField(db_column='risks', related_name='crisis_scenario_risk', to='bcm_phase1.Risk'),
        ),
        migrations.AddField(
            model_name='crisisscenario',
            name='headquarters',
            field=models.ManyToManyField(related_name='headquarter_crisis_scenario', to='configuration.Headquarter'),
        ),
    ]
