# Generated by Django 3.2.8 on 2022-06-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase1', '0003_remove_risk_services_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='organizacion_activities',
        ),
    ]
