# Generated by Django 3.2.8 on 2022-07-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0003_alter_organization_logo'),
        ('bcm_phase1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Producto'), (2, 'Servicio'), (3, 'Proceso')])),
                ('profit', models.FloatField()),
                ('recovery_time', models.DurationField()),
                ('criticality', models.SmallIntegerField(null=True)),
                ('recovery_point', models.DurationField(null=True)),
                ('maximum_recovery_time', models.DurationField(null=True)),
                ('_risks', models.ManyToManyField(related_name='risk_service_offered', to='bcm_phase1.Risk')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(max_length=30, unique=True)),
                ('names', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('earnings', models.FloatField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_staff', to='configuration.area')),
                ('headquarter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headquarter_staff', to='configuration.headquarter')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_staff', to='configuration.position')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Contratado'), (2, 'Interno')])),
                ('spending', models.FloatField()),
                ('criticality', models.SmallIntegerField(null=True)),
                ('agreement_comment', models.CharField(max_length=300)),
                ('_risks', models.ManyToManyField(related_name='risk_service_used', to='bcm_phase1.Risk')),
                ('_services_offered', models.ManyToManyField(related_name='service_offered_service_used', to='bcm_phase2.ServiceOffered')),
                ('headquarters', models.ManyToManyField(related_name='headquarter_service_used', to='configuration.Headquarter')),
                ('scale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_service_used', to='configuration.scale')),
            ],
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='_staffs',
            field=models.ManyToManyField(related_name='staff_service_offered', to='bcm_phase2.Staff'),
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_service_offered', to='configuration.area'),
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='headquarters',
            field=models.ManyToManyField(related_name='headquarter_service_offered', to='configuration.Headquarter'),
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_service_offered', to='configuration.scale'),
        ),
        migrations.CreateModel(
            name='OrganizationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('recovery_time', models.DurationField()),
                ('criticality', models.SmallIntegerField(null=True)),
                ('_headquarters', models.ManyToManyField(related_name='headquarter_organization_activity', to='configuration.Headquarter')),
                ('_risks', models.ManyToManyField(related_name='risk_organizacion_activity', to='bcm_phase1.Risk')),
                ('_services_offered', models.ManyToManyField(related_name='service_offered_organizacion_activity', to='bcm_phase2.ServiceOffered')),
                ('scale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_organization_activity', to='configuration.scale')),
            ],
        ),
        migrations.CreateModel(
            name='InterestedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Proveedor'), (2, 'Inversionista'), (3, 'Cliente'), (3, 'Accionista')])),
                ('description', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_interested_party', to='configuration.organization')),
            ],
        ),
    ]
