# Generated by Django 3.2.8 on 2022-06-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffered',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Producto'), (2, 'Servicio'), (2, 'Proceso')]),
        ),
    ]
