# Generated by Django 3.2.8 on 2022-07-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationactivity',
            old_name='services_offered',
            new_name='_services_offered',
        ),
    ]
