# Generated by Django 3.2.8 on 2022-01-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_scale_scaleview'),
        ('bcm_phase2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scaleview',
            name='scale',
        ),
        migrations.AlterField(
            model_name='organizationactivity',
            name='scale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_organization_activity', to='configuration.scale'),
        ),
        migrations.AlterField(
            model_name='serviceoffered',
            name='scale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_service_offered', to='configuration.scale'),
        ),
        migrations.AlterField(
            model_name='serviceused',
            name='scale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_service_used', to='configuration.scale'),
        ),
        migrations.DeleteModel(
            name='Scale',
        ),
        migrations.DeleteModel(
            name='ScaleView',
        ),
    ]
