# Generated by Django 3.2.8 on 2022-07-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
