# Generated by Django 3.2.8 on 2022-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase2', '0002_auto_20220203_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceused',
            name='services_offered',
        ),
        migrations.AddField(
            model_name='serviceused',
            name='_services_offered',
            field=models.ManyToManyField(related_name='service_offered_service_used', to='bcm_phase2.ServiceOffered'),
        ),
    ]
