# Generated by Django 3.2.8 on 2022-06-16 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0001_initial'),
        ('bcm_phase2', '0002_alter_serviceoffered_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffered',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Producto'), (2, 'Servicio'), (3, 'Proceso')]),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(max_length=30, unique=True)),
                ('names', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('earnings', models.FloatField()),
                ('Headquarter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headquarter_staff', to='configuration.headquarter')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_staff', to='configuration.area')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_staff', to='configuration.position')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='staffs',
            field=models.ManyToManyField(related_name='staff_service_offered', to='bcm_phase2.Staff'),
        ),
    ]
