# Generated by Django 3.2.8 on 2022-07-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase2', '0002_rename_services_offered_organizationactivity__services_offered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationactivity',
            old_name='headquarters',
            new_name='_headquarters',
        ),
    ]
