# Generated by Django 3.2.8 on 2022-07-04 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase1', '0002_initial'),
        ('bcm_phase2', '0003_rename_headquarters_organizationactivity__headquarters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceoffered',
            old_name='staffs',
            new_name='_staffs',
        ),
        migrations.RemoveField(
            model_name='serviceused',
            name='recovery_time',
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='_risks',
            field=models.ManyToManyField(related_name='risk_service_offered', to='bcm_phase1.Risk'),
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='maximum_recovery_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='recovery_point',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='serviceused',
            name='agreement_comment',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceused',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Contratado'), (2, 'Interno')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
