# Generated by Django 3.2.8 on 2022-06-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase2', '0003_auto_20220616_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Headquarter',
            new_name='headquarter',
        ),
    ]
