# Generated by Django 3.2.8 on 2022-06-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase2', '0004_rename_headquarter_staff_headquarter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceoffered',
            old_name='staffs',
            new_name='_staffs',
        ),
    ]
