# Generated by Django 3.2.8 on 2022-06-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase1', '0004_remove_risk_organizacion_activities'),
        ('bcm_phase2', '0004_serviceused__risks'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationactivity',
            name='_risks',
            field=models.ManyToManyField(related_name='risk_organizacion_activity', to='bcm_phase1.Risk'),
        ),
    ]
