# Generated by Django 3.2.8 on 2022-06-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase1', '0002_alter_risk_staffs'),
        ('bcm_phase2', '0005_rename_staffs_serviceoffered__staffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceused',
            name='recovery_time',
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='_risks',
            field=models.ManyToManyField(related_name='risk_service_offered', to='bcm_phase1.Risk'),
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='maximum_recovery_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='serviceoffered',
            name='recovery_point',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='serviceused',
            name='agreement_comment',
            field=models.CharField(default='Términos de uso genérico', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceused',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Contratado'), (2, 'Interno')], default=1),
            preserve_default=False,
        ),
    ]
