# Generated by Django 3.2.8 on 2022-06-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcm_phase1', '0002_alter_risk_staffs'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
