# Generated by Django 3.2.8 on 2022-06-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parish',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='township',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
