# Generated by Django 3.2.8 on 2022-07-04 18:41

import configuration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=configuration.models.ruta_archivo_org),
        ),
    ]
