# Generated by Django 3.2.8 on 2022-06-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20220627_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='township',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='township_parish', to='configuration.township'),
        ),
    ]
