# Generated by Django 3.2.8 on 2022-07-04 19:08

import configuration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, max_length=1000000, null=True, upload_to=configuration.models.ruta_archivo_org),
        ),
    ]
