# Generated by Django 3.2.8 on 2022-06-28 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_parish_township'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headquarter',
            name='location',
        ),
        migrations.AddField(
            model_name='headquarter',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_headquarter', to='configuration.city'),
        ),
        migrations.AddField(
            model_name='headquarter',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parish_headquarter', to='configuration.parish'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
